BlogSimple/Controllers/LocalizationController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Http;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace BlogSimple.Controllers
{
    public class LocalizationController : BaseController
    {
        [HttpPost]
        public IActionResult SetLanguage(string culture, string returnUrl)
        {
            Response.Cookies.Append(
                CookieRequestCultureProvider.DefaultCookieName,
                CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
                new CookieOptions { Expires = DateTime.UtcNow.AddYears(1) }
            );

            return LocalRedirect(returnUrl);
        }
    }
}

BlogSimple/Controllers/PostController.cs
using BlogSimple.Cache;
using BlogSimple.Infastructure.Mapper;
using BlogSimple.Model.Domain;
using BlogSimple.Models;
using BlogSimple.Repository;
using BlogSimple.Service;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;

namespace BlogSimple.Controllers
{
    public class PostController : BaseController
    {
        private IBlogPostRepository _blogPostRepository;
        private IBlogPostService _blogPostService;
        
        public PostController(IBlogPostRepository blogPostRepository, IBlogPostService blogPostService)
        {
            _blogPostRepository = blogPostRepository;
            _blogPostService = blogPostService;
            
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult GetDetail(Guid id)
        {
            var data = _blogPostRepository.GetById(id).ToModel();
            return View(data);
        }
        public IActionResult Search(string keysearch, Guid categoryId)
        {
            ViewBag.keySearch = keysearch; 
            return View("Search",new SearchKeyListPostModel { CategoryId=categoryId, KeySearch=keysearch});
        }
        [HttpPost]
        public IActionResult Comment(string comment,Guid postId)
        {
            if(!string.IsNullOrEmpty(comment))
            {
                var useriD = MyCache.GetCacheCommon.UserId;
                var ob = new Comment { Id = Guid.NewGuid(), CommentDescription = comment, BlogPostId = postId,UpdatedBy = useriD,
                    CreatedBy =useriD,UpdatedDate=DateTime.Now,CreatedDate=DateTime.Now };

                var getBlogPost = _blogPostRepository.GetById(postId);

                if (getBlogPost.Comments == null)
                    getBlogPost.Comments = new List<Comment>();

                getBlogPost.Comments.Add(ob);

                _blogPostRepository.Update(getBlogPost);
                Save();
            }
            return RedirectToAction("GetDetail", new { id=postId});
        } 
        [HttpGet]
        public FileContentResult GetImageForPost(Guid id)
        {
            try
            {
                var post = this._blogPostService.GetById(id);
                return File(post.ThumbnailImage, "image/png");
            }
            catch (Exception)
            {
                return null;
            }
        }
    }

}

BlogSimple/Views/Shared/SearchPanel.cshtml
@{ 
    var keysearch = "";
    if (ViewBag.keySearch != null)
    {
      keysearch = ViewBag.keySearch;
    }

}
<form method="post" asp-action="Search" asp-controller="Post">
  <div class="card">
    <div class="card-header">@Localizer["Search"]</div>
    <div class="card-body">
      <div class="input-group">

        <input type="text" name="keysearch" value="@keysearch" class="form-control" placeholder="Search for...">
        <span class="input-group-btn">
          <button class="btn btn-primary" type="submit">@Localizer["Go"]</button>
        </span>

      </div>
    </div>
  </div>
</form>

BlogSimple/Views/Shared/SelectLanguagePartial.cshtml
@using Microsoft.AspNetCore.Localization
@using BlogSimple.Helpers
@inject IViewLocalizer Localizer
@{
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    var availableCultures = GlobalConfiguration.SimpleCultures;
}
@if (availableCultures.Count() > 1)
{
    <li class="nav-item dropdown">
      <a href="#" class="nav-link dropdown-toggle" style="color:#9d9d9d" data-toggle="dropdown">
       Language (@requestCulture.RequestCulture.UICulture.Name)
        <span class="caret"></span>
      </a>
      <ul class="dropdown-menu lang-selector">
        @foreach (var lang in availableCultures)
        {
          if (lang.Id == requestCulture.RequestCulture.UICulture.Name)
          {
                <li class="dropdown-item"><a href="#" data-value="@lang.Id">@lang.Name <span class="glyphicon glyphicon-ok" aria-hidden="true"></span></a></li>
          }
          else
          {
                <li class="dropdown-item"><a href="#" data-value="@lang.Id">@lang.Name</a></li>
          }
        }
      </ul>
      <form asp-controller="Localization" asp-action="SetLanguage" asp-route-returnUrl="@Context.Request.Path"
            method="post" id="lang-form" role="form">
        <input type="hidden" name="culture" value="@requestCulture.RequestCulture.UICulture.Name" />
      </form>
    </li>
 
    }
   

BlogSimple/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - @Localizer["Blog Simple"]</title>


    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">@Localizer["Blog Simple"]</a>
            </div>
            <div class="navbar-collapse collapse" style="float:right">
                <ul class="nav navbar-nav">
                    @await Html.PartialAsync("SelectLanguagePartial")
                    @if (HttpContextAccessor.HttpContext.User.Identity.IsAuthenticated)
                    {
                        <li><a>@Localizer["Hello"]  @HttpContextAccessor.HttpContext.User.Identity.Name</a></li>
                        <li><a asp-area="" asp-controller="Admin" asp-action="Index">@Localizer["Admin"]</a></li>
                    }
                    
                    @if (HttpContextAccessor.HttpContext.User.Identity.IsAuthenticated)
                    {
                        <li><a asp-page="/Logout"> @Localizer["Logout"]</a></li>
                    }
                    else
                    {
                        <li><a asp-page="/Login" asp-route-ReturnUrl ="@Context.Request.Path">@Localizer["Login"]</a></li>
                        <li><a asp-page="/createuser" asp-route-ReturnUrl="@Context.Request.Path">@Localizer["Register"]</a></li>
                    }

                </ul>
              
            </div>
        </div>
    </nav>
    <div class="col-lg-1"></div>
    <div class="container body-content col-lg-7" style="margin-top:25px">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - @Localizer["Blog Simple"]</p>
        </footer>
    </div>
    <div class="col-lg-3" style="margin-top:45px">
     <!--This is search-->
       @Html.Partial("SearchPanel")
     <!--This is Category-->
      @await Component.InvokeAsync(typeof(ListCategoryViewComponent))
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

BlogSimple/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BlogSimple</title>
    <base href="~/" />

    <link rel="stylesheet" href="~/dist/vendor.css" asp-append-version="true" />
</head>
<body>
    @RenderBody()

    @RenderSection("scripts", required: false)
</body>
</html>